apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: calico.community.tanzu.vmware.com.3.19.1
  namespace: calico
spec:
  refName: calico.community.tanzu.vmware.com
  version: 3.19.1
  releaseNotes: "calico 3.19.1 https://docs.projectcalico.org/archive/v3.19/release-notes/"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      syncPeriod: 5m
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/calico@sha256:fdd6c102b3095aceace71bf540625e060d6fb2428279e375542115de44e8e02d
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
      - kapp:
          rawOptions:
            - --wait-timeout=30s
